### ISSUE TITLE
利用規約の制定

### ISSUE THREAD

**Issue by peaks-and-valleys** [kokuchi-party/kokuchi.party#39]

**Comment by peaksvndvalleys** [comment]
[kiyaku.jp](https://kiyaku.jp/index.html) を頼りつつ仕上げよう
編集が必要な点は、
- kokuchi.party はパスワードを一切保持してない
- kokuchi.party は課金要素がない

英語版は力技で作ることに

**Comment by peaks-and-valleys** [comment]
[draft](https://chatgpt.com/share/4eb168f2-ba59-4807-b5e8-d109a9debac9)

**Comment by peaks-and-valleys** [comment]
@cannorin 
利用規約をHTMLに落とし込むところまでは行ったんですけど、
言語切り替えのロジックを理解していなくてコードにどうハメたらいいかが分からないです 🙇

**Comment by cannorin** [comment]
@peaksvndvalleys `en.svelte` と `ja.svelte` を作っといたからそれぞれの内容を書き換えればおｋ～ `<h2>` とか使ってれば勝手にスタイリングもいい感じになるはず
https://github.com/kokuchi-party/kokuchi.party/pull/55

**Comment by peaks-and-valleys** [comment]
@cannorin 
プッシュしようとしたんだけど拒否られた 🥺 
リポジトリか組織の設定でやられてる可能性もあるから、その辺確認してもらえると助かる 🥺

**Comment by cannorin** [comment]
@peaksvndvalleys 今 Write 権限付与したから試してみて～～

**Comment by peaks-and-valleys** [comment]
@cannorin 
push できた！けど `Code style issues found in 2 files. ` って怒られちゃったんで、いま Prettier を走らせてみてるところです

**Comment by cannorin** [comment]
@peaksvndvalleys ドキュメント整備してなくてごめんやけど，`yarn fix` って打つだけで自動で直せるやつは直るようにしてあるから，怒られたらとりあえずそれ打ってみて！
